/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Placeholder1RouteImport } from './routes/placeholder-1'
import { Route as Placeholder2RouteImport } from './routes/placeholder-2'
import { Route as Placeholder3RouteImport } from './routes/placeholder-3'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Placeholder1Route = Placeholder1RouteImport.update({
  id: '/placeholder-1',
  path: '/placeholder-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Placeholder2Route = Placeholder2RouteImport.update({
  id: '/placeholder-2',
  path: '/placeholder-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Placeholder3Route = Placeholder3RouteImport.update({
  id: '/placeholder-3',
  path: '/placeholder-3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/placeholder-1': typeof Placeholder1Route
  '/placeholder-2': typeof Placeholder2Route
  '/placeholder-3': typeof Placeholder3Route
  '/help': typeof HelpRoute
  '/language': typeof LanguageRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/placeholder-1': typeof Placeholder1Route
  '/placeholder-2': typeof Placeholder2Route
  '/placeholder-3': typeof Placeholder3Route
  '/help': typeof HelpRoute
  '/language': typeof LanguageRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/placeholder-1': typeof Placeholder1Route
  '/placeholder-2': typeof Placeholder2Route
  '/placeholder-3': typeof Placeholder3Route
  '/help': typeof HelpRoute
  '/language': typeof LanguageRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/placeholder-1'
    | '/placeholder-2'
    | '/placeholder-3'
    | '/help'
    | '/language'
    | '/profile'
    | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/placeholder-1'
    | '/placeholder-2'
    | '/placeholder-3'
    | '/help'
    | '/language'
    | '/profile'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/placeholder-1'
    | '/placeholder-2'
    | '/placeholder-3'
    | '/help'
    | '/language'
    | '/profile'
    | '/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Placeholder1Route: typeof Placeholder1Route
  Placeholder2Route: typeof Placeholder2Route
  Placeholder3Route: typeof Placeholder3Route
  HelpRoute: typeof HelpRoute
  LanguageRoute: typeof LanguageRoute
  ProfileRoute: typeof ProfileRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder-1': {
      id: '/placeholder-1'
      path: '/placeholder-1'
      fullPath: '/placeholder-1'
      preLoaderRoute: typeof Placeholder1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder-2': {
      id: '/placeholder-2'
      path: '/placeholder-2'
      fullPath: '/placeholder-2'
      preLoaderRoute: typeof Placeholder2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder-3': {
      id: '/placeholder-3'
      path: '/placeholder-3'
      fullPath: '/placeholder-3'
      preLoaderRoute: typeof Placeholder3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Placeholder1Route: Placeholder1Route,
  Placeholder2Route: Placeholder2Route,
  Placeholder3Route: Placeholder3Route,
  HelpRoute: HelpRoute,
  LanguageRoute: LanguageRoute,
  ProfileRoute: ProfileRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
