/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PresaleRouteImport } from './routes/presale'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIndexRouteImport } from './routes/result/index'
import { Route as ResultIdRouteImport } from './routes/result/$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PresaleRoute = PresaleRouteImport.update({
  id: '/presale',
  path: '/presale',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIndexRoute = ResultIndexRouteImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/help': typeof HelpRoute
  '/language': typeof LanguageRoute
  '/presale': typeof PresaleRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
  '/tasks': typeof TasksRoute
  '/result/$id': typeof ResultIdRoute
  '/result': typeof ResultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/help': typeof HelpRoute
  '/language': typeof LanguageRoute
  '/presale': typeof PresaleRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
  '/tasks': typeof TasksRoute
  '/result/$id': typeof ResultIdRoute
  '/result': typeof ResultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/help': typeof HelpRoute
  '/language': typeof LanguageRoute
  '/presale': typeof PresaleRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
  '/tasks': typeof TasksRoute
  '/result/$id': typeof ResultIdRoute
  '/result/': typeof ResultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/help'
    | '/language'
    | '/presale'
    | '/profile'
    | '/rules'
    | '/tasks'
    | '/result/$id'
    | '/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/help'
    | '/language'
    | '/presale'
    | '/profile'
    | '/rules'
    | '/tasks'
    | '/result/$id'
    | '/result'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/help'
    | '/language'
    | '/presale'
    | '/profile'
    | '/rules'
    | '/tasks'
    | '/result/$id'
    | '/result/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  HelpRoute: typeof HelpRoute
  LanguageRoute: typeof LanguageRoute
  PresaleRoute: typeof PresaleRoute
  ProfileRoute: typeof ProfileRoute
  RulesRoute: typeof RulesRoute
  TasksRoute: typeof TasksRoute
  ResultIdRoute: typeof ResultIdRoute
  ResultIndexRoute: typeof ResultIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presale': {
      id: '/presale'
      path: '/presale'
      fullPath: '/presale'
      preLoaderRoute: typeof PresaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/': {
      id: '/result/'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  HelpRoute: HelpRoute,
  LanguageRoute: LanguageRoute,
  PresaleRoute: PresaleRoute,
  ProfileRoute: ProfileRoute,
  RulesRoute: RulesRoute,
  TasksRoute: TasksRoute,
  ResultIdRoute: ResultIdRoute,
  ResultIndexRoute: ResultIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
